name: check tagged

on: 
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  call-tagged:
    name: tagged
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    outputs:
      test1: ${{ steps.filter.outputs.test1 || steps.tagged-trigger.outputs.test1 }}

    steps:
      - uses: actions/checkout@v5

      - name: Check for modified files
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          filters: |
            test1:
              - '.github/workflows/check_tagged.yml'

      - name: Check for tagged
        id: tagged-trigger
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: |
          echo test1=true >> $GITHUB_OUTPUT
          
      - name: dump
        run: |
          echo filter outputs = [${{ steps.filter.outputs.test1 }}]
          echo trigger outputs = [${{ steps.tagged-trigger.outputs.test1 }}]

  dump-tagged:
    name: dump
    runs-on: ubuntu-latest
    needs: call-tagged
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: dump
        run: echo outputs = [${{ needs.call-tagged.outputs.test1 }}]
